CREATE TABLE users (
  user_id int GENERATED BY DEFAULT AS IDENTITY,
  username varchar (45) NOT NULL,
  password varchar (45) NOT NULL,
  email varchar (45) NOT NULL,
  PRIMARY KEY (user_id)
);
 
 
CREATE TABLE groups (
  group_id int GENERATED BY DEFAULT AS IDENTITY,
  name varchar (45) NOT NULL,
  PRIMARY KEY (group_id)
);
 
CREATE TABLE Users_Groups (
  user_id int,
  group_id int,
  PRIMARY KEY (user_id,group_id),
  CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (user_id),
  CONSTRAINT fk_group FOREIGN KEY (group_id) REFERENCES groups (group_id)
);