CREATE TABLE students (
  student_id int GENERATED BY DEFAULT AS IDENTITY,
  student_name varchar (45) NOT NULL,
  student_age int NOT NULL,
  PRIMARY KEY (student_id)
); 
 
CREATE TABLE groups (
  group_id int GENERATED BY DEFAULT AS IDENTITY,
  group_name varchar (45) NOT NULL,
  PRIMARY KEY (group_id)
);
 
CREATE TABLE students_groups (
  student_id int,
  group_id int,
  PRIMARY KEY (student_id, group_id),
  CONSTRAINT fk_student FOREIGN KEY (student_id) REFERENCES students (student_id),
  CONSTRAINT fk_group FOREIGN KEY (group_id) REFERENCES groups (group_id)
);